### ISSUE TITLE
Receiver is not multi-consumer

### ISSUE THREAD

**Issue by link2xt** [smol-rs/async-broadcast#57]
README describes `async-broadcast` as an MPMC channel similar to `async-channel`:
https://github.com/smol-rs/async-broadcast/blob/74d58892db1360b5aa94bd259034b0a279c9d1b2/README.md?plain=1#L65

However, in case of `async-broadcast` [`Receiver.recv()`](https://docs.rs/async-broadcast/0.7.0/async_broadcast/struct.Receiver.html#method.recv), [`Receiver.recv_direct()`](https://docs.rs/async-broadcast/0.7.0/async_broadcast/struct.Receiver.html#method.recv_direct) and [`Receiver.try_recv()`](https://docs.rs/async-broadcast/latest/async_broadcast/struct.Receiver.html#method.try_recv) take `&mut self` instead of `&self`. This means it is impossible to have multiple threads taking messages from a single `Receiver` side, e.g. to distribute some kind of work between threads. Naive solution of wrapping `Receiver` into async mutex does not work because any thread holding the mutex while calling `recv()` will also block any thread calling `try_recv()` so `try_recv()` will not return immediately as it should. Having multiple `Receiver`s also does not make the channel multi-consumer, in a way creating a receiver creates a new "channel" with its own buffer that is subscribed to the same broadcast sender.

Is there technical limitation that prevents making receiving calls take non-`mut` reference `&self`? If it is not possible to change e.g. for performance reasons, I think at least the documentation should be corrected to describe why `async-broadcast` differs from `async-channel` in this aspect.

**Comment by zeenix** [comment]
> This means it is impossible to have multiple threads taking messages from a single `Receiver` side,

No, it does not. You can clone the receiver as many times as you need and give it out to threads/tasks. Unlike, async-channel, each receiver gets a clone of each message sent to the channel. I'm using async-broadcast in my own project and it wouldn't be very useful for me (or perhaps anyone) if it had such a limitation.

> Is there technical limitation that prevents making receiving calls take non-`mut` reference `&self`?

At the moment, no but that's due to the current implementation using interior mutability. The reason I kept the original API (I took over someone's project) was that I thought if we had to the change the implementation for any reason, turning the reference into a mutable one will be a breaking change and a pretty inconvenient one. 

However, it's now been years and the implementation has proven to be quite solid by now. Perhaps we can change it now. @notgull any thoughts?

> I think at least the documentation should be corrected to describe why `async-broadcast` differs from `async-channel` in this aspect.

I don't think this difference is relevant. What users need to know is where they'll use -channel and where they'll use -broadcast and I think that's [covered already](https://docs.rs/async-broadcast/latest/async_broadcast/#difference-with-async-channel).

**Comment by notgull** [comment]
I think it needs to be `&mut` because the Receiver needs to update its position in the queue:

https://github.com/smol-rs/async-broadcast/blob/74d58892db1360b5aa94bd259034b0a279c9d1b2/src/lib.rs#L788

...similar to how `piper::Reader` needs to [keep track of its position in the byte slice](https://docs.rs/piper/latest/piper/struct.Reader.html).

It would be possible to rewrite the implementation to use `&self`, but it would introduce a lot more interior mutability than there already is. So, I don't think it would be worth it. But it's your call @zeenix

**Comment by zeenix** [comment]
> I think it needs to be `&mut` because the Receiver needs to update its position in the queue:

Ah right. Should have looked more carefully. Thanks. :)



> It would be possible to rewrite the implementation to use `&self`, but it would introduce a lot more interior mutability than there already is. So, I don't think it would be worth it. But it's your call @zeenix

Yeah, me neither. If we can use interior mutability, so can the user and it allows users who don't need interior mutability a a choice and avoid locking costs etc.



> So it is not a blocker for my use case, but makes `async-broadcast` not work as a drop-in replacement when someone wants to just replace existing `async-channel`

It's not supposed to be a "drop-in" replacement really. I know it would be very convenient if it was but see what I wrote above.
